#!/usr/bin/env bash
# scripts/down.sh — Lifecycle: make down | make up | make reset
#
# down : scale all workloads to 0 (seal Vault last), then scripts/crc-down.sh.
#        NEVER deletes PVCs, Secrets or .secrets/.
# up   : scripts/crc-up.sh, scale seal Vault, unseal, seal agent, main Vault,
#        identity, workloads, app; then make verify.
#        If the seal agent cannot authenticate (expired secret-id > 24 h),
#        runs make agent to re-mint it first.
# reset: DESTRUCTIVE — requires typing 'shift-gear' (or CONFIRM=shift-gear; DRY_RUN=1 lists only). Deletes namespaces and
#        moves generated state to .secrets/archive/<timestamp>/. Keeps CRC VM.
set -euo pipefail
SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "${SCRIPT_DIR}/common.sh"

require_cmd oc

action="${1:-}"
[[ -n "${action}" ]] || { echo "Usage: $0 down|up|reset" >&2; exit 1; }

require_kubeconfig

scale() {
  local ns="$1" selector="$2" replicas="$3"
  oc -n "${ns}" scale deployment --selector "${selector}" --replicas "${replicas}" 2>/dev/null || true
}

case "${action}" in

# ── down ──────────────────────────────────────────────────────────────────────
down)
  info "Scaling down — application namespaces first, seal Vault last"
  for ns in sg-app sg-workloads sg-identity; do
    info "  scale ${ns} → 0"
    oc -n "${ns}" scale deployment --all --replicas 0 2>/dev/null || true
  done
  info "  scale sg-vault → 0 (statefulset)"
  oc -n sg-vault scale statefulset vault --replicas 0 2>/dev/null || true
  info "  scale seal-agent → 0"
  oc -n sg-vault-seal scale deployment seal-agent --replicas 0 2>/dev/null || true
  info "  scale sg-vault-seal → 0 (statefulset)"
  oc -n sg-vault-seal scale statefulset vault-seal --replicas 0 2>/dev/null || true
  ok "All workloads scaled to 0"
  "${SCRIPT_DIR}/crc-down.sh"
  ok "down complete"
  ;;

# ── up ────────────────────────────────────────────────────────────────────────
up)
  info "Bringing the lab up"
  "${SCRIPT_DIR}/crc-up.sh"
  require_kubeconfig

  info "Scaling seal Vault up"
  oc -n sg-vault-seal scale statefulset vault-seal --replicas 1
  info "Waiting for seal Vault pod"
  oc -n sg-vault-seal wait pod -l app.kubernetes.io/instance=vault-seal \
    --for=condition=Ready --timeout=120s 2>/dev/null || true

  info "Unsealing seal Vault"
  "${SCRIPT_DIR}/ansible-run.sh" unseal

  info "Scaling seal-agent up"
  oc -n sg-vault-seal scale deployment seal-agent --replicas 1

  # If the agent cannot authenticate, the secret-id expired — re-mint it
  if ! oc -n sg-vault-seal wait deployment seal-agent \
      --for=condition=Available --timeout=60s 2>/dev/null; then
    warn "Seal agent not ready — secret-id may have expired. Running make agent..."
    "${SCRIPT_DIR}/ansible-run.sh" agent
  fi

  info "Scaling main Vault cluster up"
  oc -n sg-vault scale statefulset vault --replicas 3
  info "Waiting for Vault pods (auto-unseals through seal agent)"
  oc -n sg-vault wait pod -l app.kubernetes.io/name=vault \
    --for=condition=Ready --timeout=300s 2>/dev/null || true

  info "Scaling identity stack up"
  oc -n sg-identity scale deployment --all --replicas 1 2>/dev/null || true

  info "Scaling workloads up"
  oc -n sg-workloads scale deployment --all --replicas 1 2>/dev/null || true

  info "Scaling sg-app up"
  oc -n sg-app scale deployment --all --replicas 1 2>/dev/null || true

  info "Running make verify"
  make -C "${ROOT_DIR}" verify || warn "make verify: some checks failed — see output above"

  ok "up complete"
  ;;

# ── reset ─────────────────────────────────────────────────────────────────────
reset)
  # Moves (never deletes) everything a fresh cluster must not inherit into
  # .secrets/archive/<timestamp>/, then deletes the lab namespaces.
  # Kept on purpose (the operator's, or valid across clusters): .env, the pull
  # secret, the kubeconfig the cluster scripts manage (.secrets/kube/config)
  # and the lab CA (.secrets/tls/ca.key, ca.srl, pub/ca.pem), so 'make trust'
  # survives a reset. Leaf certificates are regenerated by 'make lab'.
  #   DRY_RUN=1 make reset            list what would happen, change nothing
  #   CONFIRM=shift-gear make reset   non-interactive confirmation
  targets=()
  for f in "${SECRETS_DIR}/seal-init.json" "${SECRETS_DIR}/vault-init.json" \
    "${SECRETS_DIR}/tokens" "${SECRETS_DIR}/terraform" "${SECRETS_DIR}/vault" \
    "${SECRETS_DIR}/kube/ingress-ca.pem" "${BUILD_DIR}"; do
    [[ -e "${f}" ]] && targets+=("${f}")
  done
  while IFS= read -r f; do targets+=("${f}"); done < <(
    find "${SECRETS_DIR}/tls" -maxdepth 2 -type f \( -name '*.key' -o -name '*.crt' \) \
      ! -name 'ca.key' 2>/dev/null | sort)
  namespaces=(sg-app sg-workloads sg-identity sg-vault sg-vault-seal)

  if [[ "${DRY_RUN:-0}" == "1" ]]; then
    info "DRY RUN: make reset would move into .secrets/archive/<timestamp>/:"
    for f in "${targets[@]}"; do printf '  %s\n' "${f#"${ROOT_DIR}"/}"; done
    info "and delete the namespaces: ${namespaces[*]}"
    info "and the cluster-scoped objects Terraform owns: Subscription + CSV vault-secrets-operator, ClusterRoleBinding vault-token-reviewer"
    info "Kept: .env, the pull secret, .secrets/kube/config, the lab CA. Nothing changed."
    exit 0
  fi

  if [[ "${CONFIRM:-}" != "shift-gear" ]]; then
    printf '\033[31mDESTRUCTIVE RESET\033[0m — type "shift-gear" to confirm: '
    read -r confirm
    [[ "${confirm}" == "shift-gear" ]] || { warn "Aborted."; exit 1; }
  fi

  ts="$(date -u +%Y%m%dT%H%M%SZ)"
  archive="${SECRETS_DIR}/archive/${ts}"
  mkdir -p "${archive}"
  chmod 700 "${SECRETS_DIR}/archive" "${archive}"

  info "Archiving generated state to ${archive#"${ROOT_DIR}"/}"
  for f in "${targets[@]}"; do
    rel="${f#"${ROOT_DIR}"/}"
    mkdir -p "${archive}/$(dirname "${rel}")"
    mv "${f}" "${archive}/${rel}"
  done

  info "Deleting OpenShift namespaces"
  for ns in "${namespaces[@]}"; do
    oc delete namespace "${ns}" --ignore-not-found 2>/dev/null || true
  done

  # Cluster-scoped objects Terraform owns outlive the namespaces; with the
  # state archived, the next apply would fail on "already exists".
  info "Deleting the cluster-scoped objects Terraform owns"
  csv="$(oc -n openshift-operators get subscription vault-secrets-operator \
    -o jsonpath='{.status.installedCSV}' 2>/dev/null || true)"
  oc -n openshift-operators delete subscription vault-secrets-operator --ignore-not-found 2>/dev/null || true
  [[ -n "${csv}" ]] && oc -n openshift-operators delete csv "${csv}" --ignore-not-found 2>/dev/null || true
  oc delete clusterrolebinding vault-token-reviewer --ignore-not-found 2>/dev/null || true

  ok "Reset complete — CRC VM preserved, lab CA kept ('make trust' still applies)."
  info "Next: 'make lab' to rebuild on this VM, or 'make crc-reset && make lab' for a fresh VM."
  ;;

*)
  echo "Usage: $0 down|up|reset" >&2
  exit 1
  ;;
esac
